### ISSUE TITLE
Release-v4.9 fails with SyntaxError

### ISSUE THREAD

**Issue by TheGuv** [Psynosaur/DATV-Red#29]
On Linux:

```
$ ./DATV-Start-Linux.sh
Starting DATV-Red...
/home/opt/DATV-Red-rel/DATV-Red-v4.9-1/npm/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/credentials.js:389
                const newCredentialKeys = Object.keys(newCreds?.map || [])
                                                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/opt/DATV-Red-rel/DATV-Red-v4.9-1/npm/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js:24:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
```
$ apt policy nodejs
nodejs:
  Installed: 12.22.9~dfsg-1ubuntu3.6
```

The current 'main' tree does start, however the web UI is protected by unspecified credentials.
EDIT: Wait, no password when I added '/ui' to the URL. I didn't see that mentioned anywhere. 'main' tree works fine.

**Comment by Psynosaur** [comment]
Give `npm/node` execute rights with `chmod +x`

You're using node 12 dude, the project uses `Node 21`.

Read the wiki https://github.com/Psynosaur/DATV-Red/wiki#linux-specific

Do not concern yourself with the back end password.

**Comment by TheGuv** [comment]
Yes, and yes I was.
I did read the wiki and the terminal output but clearly I am blind, or more likely my face is covered with my hands due to being daft.
Thanks for the clues. Sorry for the noise.
